import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>APP TITLE</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/applogo.png" />
      </Head>
    </div>
  );
}
