"use client";

import Image from "next/image";
import { motion } from "framer-motion";
import Head from "next/head";

export default function Login() {
  return (
    <aside>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/applogo.png" />
      </Head>
      <div className="flex md:flex-row  flex-col">
        <section className="bg-gray-50  md:w-5/12">
          <div className="flex flex-col items-center justify-center px-6 py-8 mx-auto md:h-screen lg:py-0">
            <motion.span
              initial={{
                opacity: 0,
              }}
              animate={{
                opacity: 1,
              }}
              transition={{
                duration: 1.5,
              }}
              className="flex flex-col text-center items-center mb-6 text-2xl font-semibold text-gray-900 "
            >
              <Image
                className="w-8 h-8 ml-2"
                src={"/images/applogo.png"}
                alt="logo"
                width={100}
                height={100}
              />
              로그인
            </motion.span>
            <div className="w-full bg-white rounded-lg   md:mt-0 sm:max-w-md xl:p-0  ">
              <div className="p-6 space-y-4 md:space-y-6 sm:p-8">
                <form className="space-y-4 md:space-y-6" action="#">
                  <div>
                    <motion.label
                      initial={{
                        opacity: 0,
                      }}
                      animate={{
                        opacity: 1,
                      }}
                      transition={{
                        duration: 1.5,
                      }}
                      htmlFor="email"
                      className="block mb-2 text-sm font-medium text-gray-900 "
                    >
                      이메일
                    </motion.label>
                    <input
                      type="email"
                      name="email"
                      id="email"
                      className="bg-gray-50 border border-none text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5"
                      placeholder="이메일(아이디)을 입력해 주세요."
                      required
                    />
                  </div>
                  <div>
                    <motion.label
                      initial={{
                        opacity: 0,
                      }}
                      animate={{
                        opacity: 1,
                      }}
                      transition={{
                        duration: 1.5,
                      }}
                      htmlFor="password"
                      className="block mb-2 text-sm font-medium text-gray-900 "
                    >
                      비밀번호
                    </motion.label>
                    <input
                      type="password"
                      name="password"
                      id="password"
                      placeholder="비밀번호를 입력해 주세요"
                      className="bg-gray-50 border border-none text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 "
                      required
                    />
                  </div>

                  <button className="w-full text-white bg-[#4dd399] hover:bg-primary-700 p-2 rounded-sm">
                    로그인
                  </button>
                  <div className="items-center">
                    <div className="flex">
                      <div className="flex items-center h-5">
                        <input
                          id="remember"
                          aria-describedby="remember"
                          type="checkbox"
                          className="w-4 h-4 border border-gray-300  hover:cursor-pointer rounded  focus:[#4dd399] bg-[#4dd399] focus:ring-[#4dd399] "
                          required
                        />
                      </div>
                      <div className="ml-3 text-sm">
                        <label htmlFor="remember" className="text-gray-500 ">
                          자동 로그인
                        </label>
                      </div>
                    </div>
                  </div>
                  <p className="text-sm font-light text-center text-gray-500 ">
                    아이디 · 비밀번호 찾기
                  </p>
                </form>
              </div>
            </div>
          </div>
        </section>
        <section className="hidden md:block md:w-auto">
          {/*  <Image
            src={"/images/applogo.png"}
            width={100}
            height={100}
            alt="wallpaper"
            className=""
          /> */}
        </section>
      </div>
    </aside>
  );
}
